import type { Card } from '@prisma/client';

/** A minimal but complete Card row used across API tests. */
export function makeCard(overrides: Partial<Card> = {}): Card {
  return {
    id: 'card_test_1',
    slug: 'test-card',
    name: 'Test Rewards Card',
    issuer: 'Test Bank',
    network: 'VISA',
    category: 'REWARDS',
    tier: 'MID',
    summary: 'A card used in tests.',
    joiningFee: 500,
    annualFee: 500,
    feeWaiverSpend: 200000,
    forexMarkup: 3.5,
    minIncomeSalaried: 300000,
    minIncomeSelfEmployed: 400000,
    minAge: 21,
    maxAge: 60,
    minCreditScore: 700,
    rewardType: 'POINTS',
    baseRewardRate: 1,
    rewardMultipliers: { DINING: 5 },
    cappedMonthlyReward: null,
    welcomeBenefit: null,
    milestoneBenefit: null,
    domesticLoungeVisits: 4,
    internationalLoungeVisits: 0,
    fuelSurchargeWaiver: true,
    fuelWaiverMonthlyCap: 250,
    golfBenefit: false,
    insuranceCoverInr: null,
    conciergeService: false,
    highlights: ['Great for testing'],
    tags: ['rewards', 'test'],
    imageUrl: null,
    officialUrl: 'https://example.com',
    rating: 4,
    popularity: 50,
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
    ...overrides,
  } as Card;
}
